### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by zhangwdd** [likly/ProcessOnRegister#1]
登录哪里出问题了

**Comment by likly** [comment]
因ProcessOn官网邀请注册流程发生变更，现有版本暂时不支持新的注册流程

**Comment by likly** [comment]
试下  [0.0.2-SNAPSHOT](https://github.com/likly/ProcessOnRegister/releases/tag/0.0.2-SNAPSHOT)

**Comment by iimik** [comment]
> 登录哪里出问题了

因ProcessOn官网邀请注册流程发生变更，现有版本暂时不支持新的注册流程，试下 [0.0.2-SNAPSHOT](https://github.com/likly/ProcessOnRegister/releases/tag/0.0.2-SNAPSHOT)
