### ISSUE TITLE
浏览器自动控制无法加载打开微信二维码扫描页面

### ISSUE THREAD

**Issue by RocketTH** [likly/ProcessOnRegister#2]
报错如下

![image](https://user-images.githubusercontent.com/14861287/114305618-8730cd00-9b0b-11eb-81a3-8625a2ccc5da.png)

**Comment by iimik** [comment]
页面元素发生变化，请尝试新的版本 [0.0.3-SNAPSHOT](https://github.com/likly/ProcessOnRegister/releases/tag/0.0.3-SNAPSHOT)。
