### ISSUE TITLE
邮箱绑定及解绑是手动操作么？

### ISSUE THREAD

**Issue by yaoper** [likly/ProcessOnRegister#4]
今天下午尝试了下，走到“暂不绑定，直接登录”这一步步骤程序报错，错误和 #3 一样。接下来就是再次扫码登录，然后绑定邮箱并解绑微信的绑定关系，然后用这个微信再次扫码登录注册新账号。

请问正常的流程是这样的吗？感谢。

**Comment by iimik** [comment]
1、邮箱绑定是半自动的，验证码识别在部分情况下会失败，需要手动介入一下；解绑是自动的
2、本地安装的`ChromeDriver`的什么版本的，猜测应该是版本不一致的问题，可以提供一下使用的版本，方便看下具体的问题

**Comment by yaoper** [comment]
> 1、邮箱绑定是半自动的，验证码识别在部分情况下会失败，需要手动介入一下；解绑是自动的
是的，后来我调试了下程序，验证码获取会存在超时获取不到验证码的情况。
> 2、本地安装的`ChromeDriver`的什么版本的，猜测应该是版本不一致的问题，可以提供一下使用的版本，方便看下具体的问题
我的Chrome版本是92.0.4515.131，下载的ChromeDriver的版本也是与之对应的版本。

**Comment by iimik** [comment]
在本地试了一下，发现以下问题：
1、使用的临时邮箱不能直接访问了，需要使用VPN，请查看下你的网络环境是否可以访问该临时邮箱
```url
https://www.linshiyouxiang.net/
```
2、该邮箱服务更换了部分域名邮箱地址，因此可能会收不到验证码，现已同步目前的域名邮箱地址如下：
* linshiyouxiang.net
* iffygame.com
* maileven.com
* smuggroup.com
* chapedia.net
* meantinc.com
* powerencry.com
* worldzipcodes.net
* chapedia.org
* chasefreedomactivate.com
* wellsfargocomcardholders.com

以上问题已在 [0.0.4-SNAPSHOT](https://github.com/ilikly/ProcessOnRegister/releases/tag/0.0.4-SNAPSHOT)中修复，请重新下载并尝试。

如有问题，请及时反馈！
